### ISSUE TITLE
cracklibjs says password is valid that cracklib-check rejects

### ISSUE THREAD

**Issue by stormbard** [zacanger/cracklibjs#8]
# Is this a feature request or a bug?
Bug

# Expected behavior:
Tester@123 should be rejected. Passwords that are simple and based of dictionary words should also be rejected.
```javascript
> validate('Tester@123')
'Password is too common'
```

Running cracklib-check
```sh
$ echo 'Tester@123' | cracklib-check
Tester@123: it is based on a dictionary word
```   

# Actual behavior:
Using the example in the readme I run with a dict file extracted from the cracklib db I got the following.
```js
> validate('Tester@123')
'Tester@123'
```

# Environment info (relevant browser, OS, etc.; run `npx envinfo`):
Mac OS X Catalina  10.15.7
Node: 14.6.0 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
I installed cracklib via homebrew for comparison and am just using the standard dictionary that comes with it.

**Comment by zautumnz** [comment]
Fixed in 4.0.5
